### ISSUE TITLE
AuthInfoRequired

### ISSUE THREAD

**Issue by felzmann** [leoarnold/puppet-cups#15]
Sorry for bringing this up again.

The AuthInfoRequired is actually a queue option, for example:
```
<Printer 155LG.G10-ToshibaEstudio2540c>
UUID urn:uuid:27a6e0d3-c410-3f47-7bf3-6c403d5dfdea
AuthInfoRequired username,password
Info 155LG.G10-ToshibaEstudio2540c
MakeModel TOSHIBA ColorMFP
DeviceURI smb://uom-print.unimelb.edu.au/155LG.G10-ToshibaEstudio2540c
State Stopped
StateTime 1486697339
ConfigTime 1486697341
Type 8433884
Accepting No
Shared No
JobSheets none none
QuotaPeriod 0
PageLimit 0
KLimit 0
OpPolicy default
ErrorPolicy retry-job
</Printer>
```

Other options are "none" and "negotiate". This will trigger cups to prompt for a password before shelling out the print command. 

I think you implemented it as a printer option. Could that be changed please? Sorry for the confusion.

Thanks.
Uli

**Comment by leoarnold** [comment]
In CUPS, there are two kinds of queues: printers and classes (with the self-titled `.conf` files). They are "same same, but different". In particular, option handling is the same for both.

When it comes to options, there are two kinds. I use the terms "native" (saved in `(printers|classes).conf`) and "vendor" (saved in `/etc/cups/ppd/MyQueue.pdd`).

All options are set the same way:
```shell
sudo lpadmin -p MyQueue -o option-name=value
```
As you can see, this is indifferent of the fact, whether the queue is a class or printer, or whether the option is native or vendor.
**Note:** We are using `lpadmin` here, because `lpoptions` would modify `/etc/cups/lpoptions` or the files in `~/.cups`. In order to gain the privilege to use `lpadmin`, we use `sudo` (because Puppet runs as `root` anyway).

You can check this for your setup as follows:

1. Remove authentication:
```Shell
sudo lpadmin -p 155LG.G10-ToshibaEstudio2540c -o auth-info-required=none
```
2. Verify that authentication is gone
3. Enforce authentication:
```Shell
sudo lpadmin -p 155LG.G10-ToshibaEstudio2540c -o auth-info-required=username,password
```
4. Verify that authentication is back in place.

If this worked in your setup, then the next release of the module will work for you.

**Note:** In the testing procedure described above, do not rely on reading `printers.conf`. CUPS changes options immediately in memory, but only periodically updates `printers.conf` (every couple of minutes I guess). So, to test whether authentication is in effect or not, please try to print a document.

**Comment by leoarnold** [comment]
Assuming "fixed" due to no response.

**Comment by felzmann** [comment]
Yes, indeed.
Sorry for the lack of response.

Uli
