### ISSUE TITLE
How to set purge_unmanaged_queues => 'true'

### ISSUE THREAD

**Issue by IHOPKCdavidgagne** [leoarnold/puppet-cups#8]
**Given** Centos7 with Ruby 2.0.0, Puppet 3.8.7 and CUPS 1.6.3.

**When** I apply the manifest

```puppet
include '::cups'

class { '::cups':
  purge_unmanaged_queues => 'true'
}
```

**In order to** Remove unwanted queues

**Then** I get the error message:

```Shell
Error: Could not parse for environment production: Syntax error at 'purge_unmanaged_queues' at /root/cups-install/cups.pp:4:2 on node...
```

**Comment by IHOPKCdavidgagne** [comment]
Still learning puppet, not sure how to set the global attributes.

**Comment by leoarnold** [comment]
First, there is a contradiction in your manifest: If you use the line

```puppet
include '::cups'
```
that means you want to use `Class[Cups]` with default values. Since you do want to apply some custom settings, you should only provide

```puppet
class { '::cups':
  purge_unmanaged_queues => true,
}
```

Note that I removed the quotes around the keyword `true`, because `true` is boolean while `'true'` is a string. This probably caused the syntax error.

**Comment by IHOPKCdavidgagne** [comment]
Thanks!
